export const TRAINING_TYPE_LOAD_REQUEST = "TRAINING_TYPE_LOAD_REQUEST";
export const TRAINING_TYPE_LOAD_SUCCESS = "TRAINING_TYPE_LOAD_SUCCESS";
export const TRAINING_TYPE_LOAD_FAIL = "TRAINING_TYPE_LOAD_FAIL";
export const TRAINING_TYPE_LOAD_RESET = "TRAINING_TYPE_LOAD_RESET";

export const CREATE_TRAINING_TYPE_REQUEST = "CREATE_TRAINING_TYPE_REQUEST";
export const CREATE_TRAINING_TYPE_SUCCESS = "CREATE_TRAINING_TYPE_SUCCESS";
export const CREATE_TRAINING_TYPE_FAIL = "CREATE_TRAINING_TYPE_FAIL";
export const CREATE_TRAINING_TYPE_RESET = "CREATE_TRAINING_TYPE_RESET";

