export const TRAINING_LOAD_REQUEST = "TRAINING_LOAD_REQUEST";
export const TRAINING_LOAD_SUCCESS = "TRAINING_LOAD_SUCCESS";
export const TRAINING_LOAD_FAIL = "TRAINING_LOAD_FAIL";
export const TRAINING_LOAD_RESET = "TRAINING_LOAD_RESET";


export const TRAINING_LOAD_SINGLE_FAIL = "TRAINING_LOAD_SINGLE_FAIL";
export const TRAINING_LOAD_SINGLE_REQUEST = "TRAINING_LOAD_SINGLE_REQUEST";
export const TRAINING_LOAD_SINGLE_RESET = "TRAINING_LOAD_SINGLE_RESET";
export const TRAINING_LOAD_SINGLE_SUCCESS = "TRAINING_LOAD_SINGLE_SUCCESS";

export const REGISTER_TRAINING_REQUEST = "REGISTER_TRAINING_REQUEST";
export const REGISTER_TRAINING_SUCCESS = "REGISTER_TRAINING_SUCCESS";
export const REGISTER_TRAINING_FAIL = "REGISTER_TRAINING_FAIL";
export const REGISTER_TRAINING_RESET = "REGISTER_TRAINING_RESET";

export const DELETE_TRAINING_REQUEST = "DELETE_TRAINING_REQUEST";
export const DELETE_TRAINING_SUCCESS = "DELETE_TRAINING_SUCCESS";
export const DELETE_TRAINING_FAIL = "DELETE_TRAINING_FAIL";
export const DELETE_TRAINING_RESET = "DELETE_TRAINING_RESET";


export const EDIT_TRAINING_REQUEST = "EDIT_TRAINING_REQUEST";
export const EDIT_TRAINING_SUCCESS = "EDIT_TRAINING_SUCCESS";
export const EDIT_TRAINING_FAIL = "EDIT_TRAINING_FAIL";
export const EDIT_TRAINING_RESET = "EDIT_TRAINING_RESET";